title: The Great Human Experiment
email: ""
description: >-
  A Caltech course using data, computation, and first-principles reasoning
  to measure the planetary transformations driven by humans.
baseurl: ""
url: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
